### ISSUE TITLE
Fix Of htpasswd: command not found

### ISSUE THREAD

**Issue by HasanMajhali** [manishkatyan/bbb-analytics#4]
When installing using 
The command
bbb-analytics --deploy

The Error htpasswd: command not found

So I Edited the file 
/usr/lib/node_modules/bigbluebutton-analytics/bin/utils/post_install.sh
And Added After line 41
this code :
sudo apt-get install apache2-utils

And run the command 
bbb-analytics --deploy
and All is Ok

**Comment by arun-hel** [comment]
@HasanMajhali  Thanks for pointing out the issue. This is fixed in #5  so I will be closing this issue.
